version: '3.8'

services:
  streamlit:
    build: .
    ports:
      - "8501:8501"
    volumes:
      - .:/app
      - ./data:/app/data
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5000
    depends_on:
      - mlflow
    networks:
      - app-network

  mlflow:
    build: .
    command: mlflow server --backend-store-uri sqlite:///mlflow.db --default-artifact-root ./mlruns --host 0.0.0.0
    ports:
      - "5000:5000"
    volumes:
      - .:/app
      - ./mlruns:/app/mlruns
      - ./mlflow.db:/app/mlflow.db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge 