name: Python application

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.9
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .
      - name: Create test environment
        run: |
          mkdir -p data/raw data/processed
          touch data/raw/transactions_test.csv
          cp tests/.env.test .env
      - name: Test with pytest
        run: |
          python -m pytest tests/ -v --cov=src 