name: Python application

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ETHERSCAN_API_KEY: ${{ secrets.ETHERSCAN_API_KEY }}
      ETH_NODE_URL: "https://mainnet.infura.io/v3/your-project-id"
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.9
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .
      - name: Create data directories
        run: |
          mkdir -p data/raw
          mkdir -p data/processed
          touch data/raw/transactions_test.csv
      - name: Test with pytest
        run: |
          pytest tests/ -v --cov=src 